"""Predefined standard schema templates for common business workflows."""

from typing import Any, Dict, List

DEFAULT_SCHEMA_PRESETS: List[Dict[str, Any]] = [
    {
        "id": "preset-invoices-std",
        "name": "Facturas y Recibos Estándar",
        "description": "Esquema canónico para extracción de facturas, CIFs, bases imponibles y totales.",
        "document_type": "invoice",
        "fields_config_json": [
            {
                "name": "invoice_number",
                "label": "Nº Factura",
                "data_type": "string",
                "required": True,
                "description": "Número o código identificador de la factura",
                "aliases": ["factura", "n_factura", "num_factura", "invoice_no", "invoice_number", "numero", "factura_no", "nº factura"],
            },
            {
                "name": "issue_date",
                "label": "Fecha de Emisión",
                "data_type": "date",
                "required": True,
                "description": "Fecha en que se expidió el documento",
                "aliases": ["fecha", "fecha_emision", "date", "issue_date", "f_factura", "fecha emision", "f. factura"],
            },
            {
                "name": "tax_id",
                "label": "CIF / NIF / Tax ID",
                "data_type": "string",
                "required": True,
                "description": "Identificación fiscal de la empresa o cliente",
                "aliases": ["cif", "nif", "cif_nif", "vat", "rfc", "tax_id", "dni", "cuit"],
            },
            {
                "name": "customer_name",
                "label": "Cliente / Razón Social",
                "data_type": "string",
                "required": False,
                "description": "Nombre de la empresa o cliente destinatario",
                "aliases": ["cliente", "customer", "client", "razon_social", "comprador", "destinatario", "bill_to"],
            },
            {
                "name": "subtotal",
                "label": "Base Imponible (€)",
                "data_type": "number",
                "required": False,
                "description": "Importe total antes de impuestos",
                "aliases": ["base_imponible", "subtotal", "base", "net_amount", "sub_total", "importe neto"],
            },
            {
                "name": "tax_amount",
                "label": "Importe IVA (€)",
                "data_type": "number",
                "required": False,
                "description": "Cuota de impuestos aplicados",
                "aliases": ["iva", "tax", "impuestos", "igic", "vat_amount", "total_iva", "cuota iva"],
            },
            {
                "name": "total_amount",
                "label": "Total Factura (€)",
                "data_type": "number",
                "required": True,
                "description": "Importe total a pagar con impuestos incluidos",
                "aliases": ["total", "total_factura", "importe_total", "total_amount", "amount_due", "gran_total", "total_a_pagar", "total (€)"],
            },
        ],
    },
    {
        "id": "preset-inventory-std",
        "name": "Control de Inventario y Stock",
        "description": "Estandarización de catálogos de productos, unidades disponibles, costes y pasillos.",
        "document_type": "inventory",
        "fields_config_json": [
            {
                "name": "sku",
                "label": "Código SKU / Referencia",
                "data_type": "string",
                "required": True,
                "description": "Identificador único del producto o material",
                "aliases": ["sku", "ref", "referencia", "codigo", "codigo_articulo", "item_code", "cod_articulo"],
            },
            {
                "name": "product_name",
                "label": "Descripción del Artículo",
                "data_type": "string",
                "required": True,
                "description": "Nombre detallado o concepto del producto",
                "aliases": ["descripcion", "descripcion_articulo", "articulo", "producto", "nombre", "item_name", "description"],
            },
            {
                "name": "category",
                "label": "Categoría / Familia",
                "data_type": "string",
                "required": False,
                "description": "Familia o grupo al que pertenece el producto",
                "aliases": ["categoria", "familia", "tipo", "category", "seccion", "grupo"],
            },
            {
                "name": "stock_units",
                "label": "Stock Actual (Unidades)",
                "data_type": "number",
                "required": True,
                "description": "Cantidad física disponible en almacén",
                "aliases": ["stock", "stock_actual", "existencias", "unidades", "cantidad", "quantity", "qty", "in_stock"],
            },
            {
                "name": "min_stock",
                "label": "Stock Mínimo / Reorden",
                "data_type": "number",
                "required": False,
                "description": "Umbral mínimo antes de solicitar reposición",
                "aliases": ["stock_minimo", "minimo", "reorden", "min_stock", "safety_stock"],
            },
            {
                "name": "unit_cost",
                "label": "Coste Unitario (€)",
                "data_type": "number",
                "required": False,
                "description": "Coste de adquisición unitario",
                "aliases": ["coste_unitario", "coste", "precio_coste", "precio_unitario", "unit_cost", "cost", "price"],
            },
            {
                "name": "location",
                "label": "Ubicación en Almacén",
                "data_type": "string",
                "required": False,
                "description": "Pasillo, estantería o zona de almacenamiento",
                "aliases": ["ubicacion", "ubicacion_pasillo", "almacen", "pasillo", "estanteria", "bin", "rack", "location"],
            },
        ],
    },
    {
        "id": "preset-purchase-orders-std",
        "name": "Órdenes de Compra (Purchase Orders)",
        "description": "Estandarización de pedidos a proveedores con líneas de detalle y precios.",
        "document_type": "purchase_order",
        "fields_config_json": [
            {
                "name": "po_number",
                "label": "Nº Orden de Compra",
                "data_type": "string",
                "required": True,
                "description": "Número correlativo de pedido",
                "aliases": ["po_number", "n_pedido", "num_pedido", "order_number", "pedido", "purchase_order", "po number"],
            },
            {
                "name": "order_date",
                "label": "Fecha de Pedido",
                "data_type": "date",
                "required": True,
                "description": "Fecha en que se cursó la solicitud",
                "aliases": ["order_date", "fecha_pedido", "fecha", "date"],
            },
            {
                "name": "vendor_name",
                "label": "Proveedor / Vendedor",
                "data_type": "string",
                "required": True,
                "description": "Nombre de la empresa proveedora",
                "aliases": ["vendor_name", "proveedor", "vendedor", "vendor", "supplier"],
            },
            {
                "name": "item_code",
                "label": "Código Artículo",
                "data_type": "string",
                "required": False,
                "description": "Referencia del producto ordenado",
                "aliases": ["item_code", "codigo", "sku", "ref"],
            },
            {
                "name": "description",
                "label": "Descripción",
                "data_type": "string",
                "required": True,
                "description": "Concepto o descripción del item solicitado",
                "aliases": ["description", "descripcion", "concepto", "item"],
            },
            {
                "name": "quantity",
                "label": "Cantidad",
                "data_type": "number",
                "required": True,
                "description": "Número de unidades solicitadas",
                "aliases": ["quantity", "cantidad", "unidades", "qty"],
            },
            {
                "name": "unit_price",
                "label": "Precio Unitario (€)",
                "data_type": "number",
                "required": True,
                "description": "Precio pactado por unidad",
                "aliases": ["unit_price", "precio_unitario", "precio", "price"],
            },
            {
                "name": "total_price",
                "label": "Total Línea (€)",
                "data_type": "number",
                "required": False,
                "description": "Subtotal de la línea de producto",
                "aliases": ["total_price", "total", "importe_total", "total_linea"],
            },
        ],
    },
    {
        "id": "preset-payroll-std",
        "name": "Nóminas y Salarios de Personal",
        "description": "Estandarización de haberes salariales, IRPF, cuotas de Seguridad Social y neto.",
        "document_type": "payroll",
        "fields_config_json": [
            {
                "name": "employee_name",
                "label": "Nombre del Empleado",
                "data_type": "string",
                "required": True,
                "description": "Nombre completo del trabajador",
                "aliases": ["trabajador", "empleado", "nombre", "employee_name", "employee", "titular"],
            },
            {
                "name": "tax_id",
                "label": "NIF / DNI",
                "data_type": "string",
                "required": True,
                "description": "Documento de identidad fiscal del empleado",
                "aliases": ["nif", "dni", "cif", "id_empleado", "tax_id"],
            },
            {
                "name": "gross_salary",
                "label": "Total Devengado (Bruto)",
                "data_type": "number",
                "required": True,
                "description": "Total devengado antes de deducciones",
                "aliases": ["total_devengado", "salario_bruto", "bruto", "gross_salary", "devengos", "total devengado"],
            },
            {
                "name": "irpf_deduction",
                "label": "Retención IRPF (€)",
                "data_type": "number",
                "required": False,
                "description": "Retención a cuenta del IRPF",
                "aliases": ["retencion_irpf", "irpf", "retencion", "tax_deduction"],
            },
            {
                "name": "ss_deduction",
                "label": "Seguridad Social (€)",
                "data_type": "number",
                "required": False,
                "description": "Deducción por cotizaciones a la Seguridad Social",
                "aliases": ["seguridad_social", "ss", "aportacion_ss", "social_security"],
            },
            {
                "name": "net_salary",
                "label": "Líquido a Percibir (Neto)",
                "data_type": "number",
                "required": True,
                "description": "Salario neto final depositado",
                "aliases": ["liquido_total", "liquido_a_percibir", "neto", "salario_neto", "net_salary", "líquido total a percibir"],
            },
        ],
    },
]
