import { DocumentItem, DocumentDetail } from './types';

export const mockDocuments: DocumentItem[] = [
  {
    document_id: 'doc_mock_001',
    filename: 'Factura_AceroCorp_2024-001.pdf',
    file_size_bytes: 245760,
    status: 'processed',
    review_status: 'pending',
    created_at: '2026-08-15T10:30:00Z',
    check_summary: { ok: 3, warning: 1, critical: 0 },
  },
  {
    document_id: 'doc_mock_002',
    filename: 'Factura_TechParts_2024-045.xlsx',
    file_size_bytes: 128000,
    status: 'processed',
    review_status: 'reviewed',
    created_at: '2026-08-14T09:15:00Z',
    check_summary: { ok: 5, warning: 0, critical: 0 },
  },
  {
    document_id: 'doc_mock_003',
    filename: 'Factura_LogiTrans_2024-120.csv',
    file_size_bytes: 64000,
    status: 'processed',
    review_status: 'pending',
    created_at: '2026-08-13T14:45:00Z',
    check_summary: { ok: 2, warning: 2, critical: 1 },
  },
];

export const mockDocumentDetails: Record<string, DocumentDetail> = {
  doc_mock_001: {
    document_id: 'doc_mock_001',
    organization_id: 'default-org',
    filename: 'Factura_AceroCorp_2024-001.pdf',
    file_size_bytes: 245760,
    status: 'processed',
    review_status: 'pending',
    created_at: '2026-08-15T10:30:00Z',
    error_message: null,
    extraction: {
      document_type: 'invoice',
      confidence: 0.94,
      fields: {
        vendor_name: 'AceroCorp Industrial S.L.',
        vendor_tax_id: 'B-87654321',
        vendor_iban: 'ES9121000418450200051332',
        vendor_address: 'Calle Hierro 45, 28001 Madrid',
        customer_name: 'Construcciones Modernas S.A.',
        customer_tax_id: 'A-12345678',
        customer_address: 'Avda. Reforma 120, 06000 Mexico DF',
        invoice_number: 'AC-2024-001',
        issue_date: '2026-08-01',
        due_date: '2026-09-01',
        currency: 'EUR',
        subtotal: 12500.0,
        tax_total: 2625.0,
        total_amount: 15125.0,
      },
      tables: [],
      summary: 'Factura de acero estructural con 5 lineas de detalle',
      processing_time_ms: 1250,
    },
    structured_invoice: {
      vendor_name: 'AceroCorp Industrial S.L.',
      vendor_tax_id: 'B-87654321',
      vendor_iban: 'ES9121000418450200051332',
      vendor_address: 'Calle Hierro 45, 28001 Madrid',
      customer_name: 'Construcciones Modernas S.A.',
      customer_tax_id: 'A-12345678',
      customer_address: 'Avda. Reforma 120, 06000 Mexico DF',
      invoice_number: 'AC-2024-001',
      issue_date: '2026-08-01',
      due_date: '2026-09-01',
      currency: 'EUR',
      subtotal: 12500.0,
      tax_total: 2625.0,
      total_amount: 15125.0,
      items: [
        { description: 'Perfil HEB 200mm x 5m', quantity: 10, unit_price: 450.0, tax_rate_pct: 21, line_total: 4500.0 },
        { description: 'Chapas acero 3mm 2000x1000', quantity: 20, unit_price: 180.0, tax_rate_pct: 21, line_total: 3600.0 },
        { description: 'Tubos estructurales 80x80', quantity: 15, unit_price: 220.0, tax_rate_pct: 21, line_total: 3300.0 },
        { description: 'Tornilleria M16 galvanizada', quantity: 100, unit_price: 11.0, tax_rate_pct: 21, line_total: 1100.0 },
      ],
    },
    checks: [
      { check_type: 'math_validation', severity: 'ok', title: 'Validacion matematica correcta', message: 'La suma de lineas y calculo de IVA concuerdan exactamente con el total declarado.' },
      { check_type: 'tax_id_validation', severity: 'ok', title: 'NIF/CIF verificados', message: 'Los identificadores fiscales del emisor y receptor son validos segun algoritmo oficial.' },
      { check_type: 'iban_validation', severity: 'ok', title: 'IBAN valido', message: 'El IBAN bancario del emisor supera la verificacion de digito de control.' },
      { check_type: 'duplicate_check', severity: 'warning', title: 'Posible duplicado detectado', message: 'Se detecto una factura con importe similar en los ultimos 30 dias. Verificar antes de aprobar.' },
    ],
  },
  doc_mock_002: {
    document_id: 'doc_mock_002',
    organization_id: 'default-org',
    filename: 'Factura_TechParts_2024-045.xlsx',
    file_size_bytes: 128000,
    status: 'processed',
    review_status: 'reviewed',
    created_at: '2026-08-14T09:15:00Z',
    error_message: null,
    extraction: {
      document_type: 'invoice',
      confidence: 0.98,
      fields: {},
      tables: [],
      summary: 'Factura de componentes electronicos',
      processing_time_ms: 890,
    },
    structured_invoice: {
      vendor_name: 'TechParts Electronics GmbH',
      vendor_tax_id: 'DE123456789',
      vendor_iban: 'DE89370400440532013000',
      vendor_address: 'Industriestr. 7, 80335 Munchen',
      customer_name: 'FlowMind Technologies S.L.',
      customer_tax_id: 'B-12345678',
      customer_address: 'Calle Innovacion 22, 08018 Barcelona',
      invoice_number: 'TP-2024-045',
      issue_date: '2026-08-10',
      due_date: '2026-09-10',
      currency: 'EUR',
      subtotal: 8400.0,
      tax_total: 1764.0,
      total_amount: 10164.0,
      items: [
        { description: 'Modulos PLC Siemens S7-1200', quantity: 4, unit_price: 1200.0, tax_rate_pct: 21, line_total: 4800.0 },
        { description: 'Sensores proximidad inductivos', quantity: 20, unit_price: 95.0, tax_rate_pct: 21, line_total: 1900.0 },
        { description: 'Cableado apantallado 4x0.5', quantity: 100, unit_price: 17.0, tax_rate_pct: 21, line_total: 1700.0 },
      ],
    },
    checks: [
      { check_type: 'math_validation', severity: 'ok', title: 'Validacion matematica correcta', message: 'Todos los calculos cuadran perfectamente.' },
      { check_type: 'tax_id_validation', severity: 'ok', title: 'NIF/CIF verificados', message: 'Identificadores fiscales validos.' },
      { check_type: 'iban_validation', severity: 'ok', title: 'IBAN valido', message: 'IBAN verificado correctamente.' },
      { check_type: 'duplicate_check', severity: 'ok', title: 'Sin duplicados', message: 'No se detectaron facturas duplicadas.' },
      { check_type: 'amount_reasonableness', severity: 'ok', title: 'Importe razonable', message: 'El importe esta dentro de los parametros historicos para este proveedor.' },
    ],
  },
  doc_mock_003: {
    document_id: 'doc_mock_003',
    organization_id: 'default-org',
    filename: 'Factura_LogiTrans_2024-120.csv',
    file_size_bytes: 64000,
    status: 'processed',
    review_status: 'pending',
    created_at: '2026-08-13T14:45:00Z',
    error_message: null,
    extraction: {
      document_type: 'invoice',
      confidence: 0.87,
      fields: {},
      tables: [],
      summary: 'Factura de servicios de transporte internacional',
      processing_time_ms: 650,
    },
    structured_invoice: {
      vendor_name: 'LogiTrans International S.A.',
      vendor_tax_id: 'FR987654321',
      vendor_iban: 'FR7630006000011234567890189',
      vendor_address: 'Zone Aeroportuaire, 75015 Paris',
      customer_name: 'Importaciones Globales S.L.',
      customer_tax_id: 'B-87654321',
      customer_address: 'Puerto seco Sector 7, 41001 Sevilla',
      invoice_number: 'LT-2024-120',
      issue_date: '2026-08-05',
      due_date: '2026-08-25',
      currency: 'EUR',
      subtotal: 18750.0,
      tax_total: 0.0,
      total_amount: 18750.0,
      items: [
        { description: 'Flete internacional Rotterdam-Sevilla', quantity: 1, unit_price: 12000.0, tax_rate_pct: 0, line_total: 12000.0 },
        { description: 'Gestion aduanera y aranceles', quantity: 1, unit_price: 3500.0, tax_rate_pct: 0, line_total: 3500.0 },
        { description: 'Almacenamiento temporal 5 dias', quantity: 5, unit_price: 450.0, tax_rate_pct: 0, line_total: 2250.0 },
        { description: 'Seguro carga internacional', quantity: 1, unit_price: 1000.0, tax_rate_pct: 0, line_total: 1000.0 },
      ],
    },
    checks: [
      { check_type: 'math_validation', severity: 'ok', title: 'Validacion matematica correcta', message: 'Calculos cuadran correctamente.' },
      { check_type: 'tax_id_validation', severity: 'ok', title: 'NIF/CIF verificados', message: 'NIF intracomunitario valido y verificado en VIES.' },
      { check_type: 'iban_validation', severity: 'ok', title: 'IBAN valido', message: 'IBAN frances verificado.' },
      { check_type: 'reverse_charge', severity: 'warning', title: 'Inversion sujeto pasivo detectada', message: 'Factura con IVA 0% por operacion intracomunitaria. Verificar alta en VIES del emisor.' },
      { check_type: 'amount_threshold', severity: 'warning', title: 'Importe elevado para revision', message: 'Supera el umbral de revision automatica (15000 EUR). Requiere doble validacion.' },
      { check_type: 'overdue_risk', severity: 'critical', title: 'Riesgo de vencimiento', message: 'La fecha de vencimiento (2026-08-25) esta proxima. Confirmar plan de pago antes de aprobar.' },
    ],
  },
};
